name: CI

on:
    push:
        branches: ['**']
    pull_request:
        branches: ['**']

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up bun
              uses: oven-sh/setup-bun@v2
              with:
                  bun-version: 1.1.30

            - name: Install dependencies
              run: bun install --frozen-lockfile

            - name: Run lint
              run: bun lint

            - name: Run test
              run: bun run test
